### ISSUE TITLE
Código

### ISSUE THREAD

**Issue by CampioniMan** [CampioniMan/FishBay#2]
Como nosso jogo é em C#, obviamente todo o código será em C#!
## Código pronto

(marque apenas os que já estão concluídos)
- [x] Classes(Peixe, Cliente, Figura, etc)
- [x] Spawn de peixes infinitos que contém velocidade em progressão aritmética ( mais em #6 )
- [x] Botas/objetos para atrapalhar o usuário pescador
- [x] Clientes com stress diferentes(dependendo da importância)
- [x] Vara com capacidade para apenas 1 peixe ( mais em #5 )
- [x] Fila única com clientes misturados
- [x] Tela de game over (mais em #9 )
- [x] Recordes ( mais em #7 )
## Adicionais (ideias)
- [x] Easter Egg do papai noel
- [x] Peixes especiais que dão mais pontos (peixe dourado)
- [x] Dificultar o jogo ( mais em #11 )
